# Generated by Django 6.0 on 2025-12-14 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.RegexValidator(message='Имя должно содержать только кириллицу, пробелы и тире.', regex='^[а-яА-ЯёЁ\\s\\-]+$')], verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Отчество должно содержать только кириллицу, пробелы и тире.', regex='^[а-яА-ЯёЁ\\s\\-]*$')], verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.RegexValidator(message='Фамилия должна содержать только кириллицу, пробелы и тире.', regex='^[а-яА-ЯёЁ\\s\\-]+$')], verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким логином уже существует.'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Логин: латиница, цифры, тире; 3–30 символов.', regex='^[a-zA-Z0-9\\-]{3,30}$')], verbose_name='Логин'),
        ),
    ]
