# Generated by Django 6.0 on 2025-12-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menuitem_options_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(default=999, verbose_name='Остаток'),
        ),
    ]
