# Generated by Django 6.0 on 2025-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Калории, ккал'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegan',
            field=models.BooleanField(blank=True, default=False, verbose_name='Веганский'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='volume_ml',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Объём, мл'),
        ),
    ]
