# Generated by Django 6.0 on 2025-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_menuitem_calories_menuitem_is_vegan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена за шт.'),
        ),
    ]
